### ISSUE TITLE
"Test Verbindung zum Server" führt zu exception

### ISSUE THREAD

**Issue by truegreyhound** [ioBroker/ioBroker.mqtt#107]
**Describe the bug**  
Ich habe den mqtt Client konfiguriert, dass er sich gegen einen mosquitto broker per user/password anmelden muss.
Außerdem sind publish und subscribe konfiguriert.
Starte ich den Adapter, kann ich im Log sehen, dass sich dieser mit dem Broker verbindet und die konfigurierten States sendet (leider nur zum Teil, siehe nächsten Bug report).
Öffne ich nun wieder die Konfiguration und klicke auf "Test Verbindung zum Server" kommt es zum crash und der Adapter startet neu.

`2020-10-14 19:30:58.798  - [35msilly[39m: mqtt.0 (20345) States system redis pmessage io.messagebox.system.adapter.mqtt.0/io.messagebox.system.adapter.mqtt.0:{"command":"test","message":{"type":"client","webSocket":true,"url":"192.168.110.50","bind":"0.0.0.0","port":"1883","ssl":false,"certPublic":"defaultPublic","certPrivate":"defaultPrivate","certChained":"","user":"iobue","pass":"7\b\u0015\u0003`_\b$DhC\u0013s}","patterns":"XXXXXXXXXX","prefix":"","publish":"javascript.1.scriptEnabled.*,javascript.0.scriptEnabled.*,piface.*,javascript.1.watering.garden.*,javascript.0.lights.*,javascript.0.alarm.*","onchange":true,"publishAllOnStart":true,"publishOnSubscribe":true,"debug":true,"sendAckToo":true,"extraSet":false,"sendStateObject":false,"clientId":"ioBrokerPi3Ue1-MQC0","maxTopicLength":"100","sendOnStartInterval":"2000","sendInterval":"10","defaultQoS":0,"retain":true,"persistent":true,"forceCleanSession":"no"},"from":"system.adapter.admin.0","callback":{"message":{"type":"client","webSocket":true,"url":"192.168.110.50","bind":"0.0.0.0","port":"1883","ssl":false,"certPublic":"defaultPublic","certPrivate":"defaultPrivate","certChained":"","user":"iobue","pass":"7\b\u0015\u0003`_\b$DhC\u0013s}","patterns":"XXXXXXXXXX","prefix":"","publish":"javascript.1.scriptEnabled.*,javascript.0.scriptEnabled.*,piface.*,javascript.1.watering.garden.*,javascript.0.lights.*,javascript.0.alarm.*","onchange":true,"publishAllOnStart":true,"publishOnSubscribe":true,"debug":true,"sendAckToo":true,"extraSet":false,"sendStateObject":false,"clientId":"ioBrokerPi3Ue1-MQC0","maxTopicLength":"100","sendOnStartInterval":"2000","sendInterval":"10","defaultQoS":0,"retain":true,"persistent":true,"forceCleanSession":"no"},"id":233,"ack":false,"time":1602696658796},"_id":6429577}
2020-10-14 19:30:58.824  - [31merror[39m: mqtt.0 (20345) uncaught exception: Connection refused: Not authorized
2020-10-14 19:30:58.825  - [31merror[39m: mqtt.0 (20345) Error: Connection refused: Not authorized
    at MqttClient._handleConnack (/opt/iobroker/node_modules/iobroker.mqtt/node_modules/mqtt/lib/client.js:920:15)
    at MqttClient._handlePacket (/opt/iobroker/node_modules/iobroker.mqtt/node_modules/mqtt/lib/client.js:350:12)
    at work (/opt/iobroker/node_modules/iobroker.mqtt/node_modules/mqtt/lib/client.js:292:12)
    at Writable.writable._write (/opt/iobroker/node_modules/iobroker.mqtt/node_modules/mqtt/lib/client.js:302:5)
    at doWrite (/opt/iobroker/node_modules/iobroker.mqtt/node_modules/readable-stream/lib/_stream_writable.js:428:64)
    at writeOrBuffer (/opt/iobroker/node_modules/iobroker.mqtt/node_modules/readable-stream/lib/_stream_writable.js:417:5)
    at Writable.write (/opt/iobroker/node_modules/iobroker.mqtt/node_modules/readable-stream/lib/_stream_writable.js:334:11)
    at Socket.ondata (_stream_readable.js:639:20)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
2020-10-14 19:30:58.829  - [31merror[39m: mqtt.0 (20345) uncaughtException: Error: Connection refused: Not authorized
2020-10-14 19:30:58.834  - [32minfo[39m: mqtt.0 (20345) Disconnected from 192.168.110.50: undefined
2020-10-14 19:30:59.342  - [32minfo[39m: mqtt.0 (20345) terminating
2020-10-14 19:30:59.346  - [32minfo[39m: mqtt.0 (20345) Terminated (NO_ERROR): Without reason
2020-10-14 19:30:59.847  - [31merror[39m: mqtt.0 (20345) uncaught exception: Connection refused: Not authorized
2020-10-14 19:30:59.940  - [31merror[39m: host.ioBrokerPi3Ue1 Caught by controller[0]: { Error: Connection refused: Not authorized
2020-10-14 19:30:59.942  - [31merror[39m: host.ioBrokerPi3Ue1 Caught by controller[0]:     at MqttClient._handleConnack (/opt/iobroker/node_modules/iobroker.mqtt/node_modules/mqtt/lib/client.js:920:15)
2020-10-14 19:30:59.943  - [31merror[39m: host.ioBrokerPi3Ue1 Caught by controller[0]:     at MqttClient._handlePacket (/opt/iobroker/node_modules/iobroker.mqtt/node_modules/mqtt/lib/client.js:350:12)
2020-10-14 19:30:59.944  - [31merror[39m: host.ioBrokerPi3Ue1 Caught by controller[0]:     at work (/opt/iobroker/node_modules/iobroker.mqtt/node_modules/mqtt/lib/client.js:292:12)
2020-10-14 19:30:59.944  - [31merror[39m: host.ioBrokerPi3Ue1 Caught by controller[0]:     at Writable.writable._write (/opt/iobroker/node_modules/iobroker.mqtt/node_modules/mqtt/lib/client.js:302:5)
2020-10-14 19:30:59.945  - [31merror[39m: host.ioBrokerPi3Ue1 Caught by controller[0]:     at doWrite (/opt/iobroker/node_modules/iobroker.mqtt/node_modules/readable-stream/lib/_stream_writable.js:428:64)
2020-10-14 19:30:59.945  - [31merror[39m: host.ioBrokerPi3Ue1 Caught by controller[0]:     at writeOrBuffer (/opt/iobroker/node_modules/iobroker.mqtt/node_modules/readable-stream/lib/_stream_writable.js:417:5)
2020-10-14 19:30:59.945  - [31merror[39m: host.ioBrokerPi3Ue1 Caught by controller[0]:     at Writable.write (/opt/iobroker/node_modules/iobroker.mqtt/node_modules/readable-stream/lib/_stream_writable.js:334:11)
2020-10-14 19:30:59.946  - [31merror[39m: host.ioBrokerPi3Ue1 Caught by controller[0]:     at Socket.ondata (_stream_readable.js:639:20)
2020-10-14 19:30:59.946  - [31merror[39m: host.ioBrokerPi3Ue1 Caught by controller[0]:     at emitOne (events.js:116:13)
2020-10-14 19:30:59.946  - [31merror[39m: host.ioBrokerPi3Ue1 Caught by controller[0]:     at Socket.emit (events.js:211:7) code: 5 }
2020-10-14 19:30:59.947  - [31merror[39m: host.ioBrokerPi3Ue1 Caught by controller[1]: { Error: Connection refused: Not authorized
2020-10-14 19:30:59.947  - [31merror[39m: host.ioBrokerPi3Ue1 Caught by controller[1]:     at MqttClient._handleConnack (/opt/iobroker/node_modules/iobroker.mqtt/node_modules/mqtt/lib/client.js:920:15)
2020-10-14 19:30:59.947  - [31merror[39m: host.ioBrokerPi3Ue1 Caught by controller[1]:     at MqttClient._handlePacket (/opt/iobroker/node_modules/iobroker.mqtt/node_modules/mqtt/lib/client.js:350:12)
2020-10-14 19:30:59.948  - [31merror[39m: host.ioBrokerPi3Ue1 Caught by controller[1]:     at work (/opt/iobroker/node_modules/iobroker.mqtt/node_modules/mqtt/lib/client.js:292:12)
2020-10-14 19:30:59.948  - [31merror[39m: host.ioBrokerPi3Ue1 Caught by controller[1]:     at Writable.writable._write (/opt/iobroker/node_modules/iobroker.mqtt/node_modules/mqtt/lib/client.js:302:5)
2020-10-14 19:30:59.949  - [31merror[39m: host.ioBrokerPi3Ue1 Caught by controller[1]:     at doWrite (/opt/iobroker/node_modules/iobroker.mqtt/node_modules/readable-stream/lib/_stream_writable.js:428:64)
2020-10-14 19:30:59.949  - [31merror[39m: host.ioBrokerPi3Ue1 Caught by controller[1]:     at writeOrBuffer (/opt/iobroker/node_modules/iobroker.mqtt/node_modules/readable-stream/lib/_stream_writable.js:417:5)
2020-10-14 19:30:59.949  - [31merror[39m: host.ioBrokerPi3Ue1 Caught by controller[1]:     at Writable.write (/opt/iobroker/node_modules/iobroker.mqtt/node_modules/readable-stream/lib/_stream_writable.js:334:11)
2020-10-14 19:30:59.950  - [31merror[39m: host.ioBrokerPi3Ue1 Caught by controller[1]:     at Socket.ondata (_stream_readable.js:639:20)
2020-10-14 19:30:59.950  - [31merror[39m: host.ioBrokerPi3Ue1 Caught by controller[1]:     at emitOne (events.js:116:13)
2020-10-14 19:30:59.950  - [31merror[39m: host.ioBrokerPi3Ue1 Caught by controller[1]:     at Socket.emit (events.js:211:7) code: 5 }
2020-10-14 19:30:59.951  - [32minfo[39m: host.ioBrokerPi3Ue1 instance system.adapter.mqtt.0 terminated with code 0 (NO_ERROR)
2020-10-14 19:30:59.951  - [32minfo[39m: host.ioBrokerPi3Ue1 Restart adapter system.adapter.mqtt.0 because enabled
2020-10-14 19:31:29.984  - [32minfo[39m: host.ioBrokerPi3Ue1 instance system.adapter.mqtt.0 started with pid 20416
2020-10-14 19:31:31.745  - [34mdebug[39m: mqtt.0 (20416) Redis Objects: Use Redis connection: 0.0.0.0:9001
2020-10-14 19:31:31.821  - [34mdebug[39m: mqtt.0 (20416) Objects client ready ... initialize now
2020-10-14 19:31:31.830  - [34mdebug[39m: mqtt.0 (20416) Objects create System PubSub Client
2020-10-14 19:31:31.833  - [34mdebug[39m: mqtt.0 (20416) Objects create User PubSub Client
2020-10-14 19:31:31.835  - [34mdebug[39m: mqtt.0 (20416) Objects client initialize lua scripts
2020-10-14 19:31:31.859  - [34mdebug[39m: mqtt.0 (20416) Objects connected to redis: 0.0.0.0:9001
2020-10-14 19:31:31.874  - [34mdebug[39m: mqtt.0 (20416) objectDB connected
2020-10-14 19:31:31.880  - [34mdebug[39m: mqtt.0 (20416) Redis States: Use Redis connection: 0.0.0.0:9000
2020-10-14 19:31:31.892  - [34mdebug[39m: mqtt.0 (20416) States create User PubSub Client
2020-10-14 19:31:31.898  - [34mdebug[39m: mqtt.0 (20416) States create System PubSub Client
2020-10-14 19:31:31.915  - [34mdebug[39m: mqtt.0 (20416) States connected to redis: 0.0.0.0:9000
2020-10-14 19:31:31.917  - [34mdebug[39m: mqtt.0 (20416) statesDB connected
2020-10-14 19:31:32.797  - [32minfo[39m: mqtt.0 (20416) starting. Version 2.1.7 in /opt/iobroker/node_modules/iobroker.mqtt, node: v8.17.0
2020-10-14 19:31:32.884  - [35msilly[39m: mqtt.0 (20416) redis psubscribe cfg.o.system.adapter.*
2020-10-14 19:31:32.891  - [35msilly[39m: mqtt.0 (20416) redis psubscribe cfg.o.system.adapter.*
2020-10-14 19:31:32.895  - [35msilly[39m: mqtt.0 (20416) redis psubscribe cfg.o.system.adapter.*
2020-10-14 19:31:32.898  - [35msilly[39m: mqtt.0 (20416) redis psubscribe cfg.o.system.adapter.*
2020-10-14 19:31:32.902  - [35msilly[39m: mqtt.0 (20416) redis psubscribe cfg.o.system.adapter.*
2020-10-14 19:31:32.904  - [35msilly[39m: mqtt.0 (20416) redis psubscribe cfg.o.system.adapter.*
2020-10-14 19:31:32.977  - [35msilly[39m: mqtt.0 (20416) States system redis pmessage system.adapter.mqtt.0.logLevel/system.adapter.mqtt.0.logLevel:{"val":"silly","ack":true,"ts":1602696692916,"q":0,"from":"system.adapter.mqtt.0","lc":1601555338501}
2020-10-14 19:31:34.015  - [32minfo[39m: mqtt.0 (20416) Try to connect to mqtt://iobue:*******************@192.168.110.50:1883?clientId=ioBrokerPi3Ue1-MQC0
2020-10-14 19:31:34.215  - [32minfo[39m: mqtt.0 (20416) Connected to 192.168.110.50
2020-10-14 19:31:34.223  - [32minfo[39m: mqtt.0 (20416) Subscribe on: "XXXXXXXXXX"
2020-10-14 19:31:39.327  - [32minfo[39m: mqtt.0 (20416) All states published
`

**To Reproduce**  
obig beschriebene Schritte nachvollziehen

**Expected behavior**  
Ich hätte eine erfolgreich Meldung erwartet.

**Versions:**  
 - Adapter version: 2.1.9
 - JS-Controller version: 2.2.9
 - Node version: v8.17.0
 - Operating system: debian Jester auf Pi3

**Comment by Apollon77** [comment]
Test 2.1.10 please, comes out now
