### ISSUE TITLE
MQTT Adapter Client Mode crash when sending state

### ISSUE THREAD

**Issue by BernhardLinz** [ioBroker/ioBroker.mqtt#290]
I am using the MQTT-Adapter in Client-Mode with a existing mosquitto server on same host (127.0.0.1).

I try to send "OFF" to the state 
`mqtt.0.cmnd.K51-Buero-Licht.POWER`

The Adapter 4.0.0 will crash:
```
2022-05-13 09:09:34.861  - info: mqtt.0 (1617963) starting. Version 4.0.0 in /opt/iobroker/node_modules/iobroker.mqtt, node: v14.19.2, js-controller: 4.0.23
--
2022-05-13 09:09:35.258  - info: mqtt.0 (1617963) Try to connect to mqtt://127.0.0.1:1883 with clientId=mqtt.mqtt.0and credentials mqtt:*******************
2022-05-13 09:09:35.306  - info: mqtt.0 (1617963) Connected to 127.0.0.1
2022-05-13 09:09:35.308  - info: mqtt.0 (1617963) Subscribe on "#"
2022-05-13 09:09:59.720  - info: mqtt.0 (1617963) send2Server mqtt.0.cmnd.K51-Buero-Licht.POWER[undefined]
2022-05-13 09:09:59.724  - info: mqtt.0 (1617963) send2Server mqtt.0.cmnd.K51-Buero-Licht.POWER[cmnd/K51-Buero-Licht/POWER]
2022-05-13 09:09:59.726  - error: mqtt.0 (1617963) uncaught exception: Cannot read property 'obj' of undefined
2022-05-13 09:09:59.727  - error: mqtt.0 (1617963) TypeError: Cannot read property 'obj' of undefined
at publishMessage (/opt/iobroker/node_modules/iobroker.mqtt/lib/client.js:95:29)
at send2Server (/opt/iobroker/node_modules/iobroker.mqtt/lib/client.js:77:9)
at Immediate.<anonymous> (/opt/iobroker/node_modules/iobroker.mqtt/lib/client.js:57:17)
at processImmediate (internal/timers.js:466:21)
2022-05-13 09:09:59.728  - error: mqtt.0 (1617963) Cannot read property 'obj' of undefined
2022-05-13 09:09:59.729  - error: mqtt.0 (1617963) uncaughtException: TypeError: Cannot read property 'obj' of undefined
2022-05-13 09:09:59.744  - info: mqtt.0 (1617963) Disconnected from 127.0.0.1: undefined
2022-05-13 09:10:00.238  - info: mqtt.0 (1617963) terminating
2022-05-13 09:10:00.240  - warn: mqtt.0 (1617963) Terminated (UNCAUGHT_EXCEPTION): Without reason
2022-05-13 09:10:00.915  - error: host.iobroker instance system.adapter.mqtt.0 terminated with code 6 (UNCAUGHT_EXCEPTION)

````
The JSON of the state:
```
{
  "common": {
    "name": "cmnd/K51-Buero-Licht/POWER",
    "write": true,
    "read": true,
    "role": "variable",
    "desc": "mqtt client variable",
    "type": "string"
  },
  "native": {
    "topic": "cmnd/K51-Buero-Licht/POWER"
  },
  "type": "state",
  "from": "system.adapter.mqtt.0",
  "user": "system.user.admin",
  "ts": 1615150538032,
  "_id": "mqtt.0.cmnd.K51-Buero-Licht.POWER",
  "acl": {
    "object": 1636,
    "state": 1636,
    "owner": "system.user.admin",
    "ownerGroup": "system.group.administrator"
  }
}
```

**Comment by BernhardLinz** [comment]
V4.0.1 looking good, all work as expected
