### ISSUE TITLE
Version 4 - and also mqtt-client does no longer support publication of other iob states directly. 

### ISSUE THREAD

**Issue by mickym2** [ioBroker/ioBroker.mqtt#293]
With version 4 - it is no longer possible to publish iob states out of the mqtt-instances. 
Even in Version 3.0.6 the mask to specify iob states were disappeard - even if with this version the states will still be published. 

I assume that this is intended - but why and will there be another possibility to publish iob states directly out of the mqtt adapter instances?

I understand in principle that it does not fit to the new rules that no adapter can indirectly write into name spaces of another adapter, but why it was not possible to keep the publishing functionality.

**Comment by mickym2** [comment]
Here a link to the iobroker forum, if this should not discussed here: https://forum.iobroker.net/topic/54903/mqtt-kein-publish-von-iob-states-ausserhalb-mqtt-scopes

**Comment by Apollon77** [comment]
For a "client" it was never intended that it publishes kind of all (or specified by the mast - that was only shown if server was selected - because of this) states and tthis confused many people because it was a completely unexpected behaviour.

Because of this it was decided that a "client" should only publish his own states aka "His own namespace".

Whats the usecase that a "client" can display whatsoever other states?

**Comment by mickym2** [comment]
It was possible to publish states of other adapter to a mqtt broker (external broker). So I could understand that it is dangerous for subscriptions if the mqtt adapter will write in to foreign adapter name spaces, but publishing other adapter states would not create any problems as states are only read and written into an external broker.

**Comment by mickym2** [comment]
All my mqtt instances were configured as clients - here I found at least on screenshot which shows that I could specify topics to publish. I think I have another screenshot with my second instance as well - where I published the states of my devices of the tr.064 adapter.

https://forum.iobroker.net/assets/uploads/files/1651595852122-657254d0-761a-4b6d-b778-47dfb7a00fac-image.png

**Comment by Apollon77** [comment]
As said, it was possible, but never intended ... will discuss this with @GermanBluefox 

So you configured an mqtt adapter as client and published states over to your broker. right?

The chakllenge is as you understood already that MQTT is 100% bidirectional here which means that the server can also publish/write these states and people would also expect this to be working ...

**Comment by mickym2** [comment]
So i found my posting with screenshots of both mqtt Adapters 

https://forum.iobroker.net/topic/49898/korrekte-verwendung-des-mqtt-adapters/9?_=1652565058221

So I could configure normally each mqtt client to publish only topics as well - and this is what I did

**Comment by mickym2** [comment]
> As said, it was possible, but never intended ... will discuss this with @GermanBluefox
> 
> So you configured an mqtt adapter as client and published states over to your broker. right?
> 
> The chakllenge is as you understood already that MQTT is 100% bidirectional here which means that the server can also publish/write these states and people would also expect this to be working ...

So may be in addition to the current functionality - they fields could be returned back to the client configuration - with a note that these states are only to publish and not for subscription. As shown i used an own prefix to have these states within an own name space (topic) in the mqtt broker.

**Comment by Apollon77** [comment]
It was allowed again, please check GitHub version and give Feedback

**Comment by mickym2** [comment]
So I returned to my configuration working with mqtt version 3.0.6. Then I tried to update the new mqtt-Adapter 4.0.2 - however I had first to update my admin. 

The update rans properly: 

`$ iobroker url ioBroker/ioBroker.mqtt --host MWHome

install ioBroker/ioBroker.mqtt

NPM version: 6.14.17

Installing ioBroker/ioBroker.mqtt... (System call)

+ iobroker.mqtt@4.0.2updated 3 packages in 313.738s

119 packages are looking for funding run `npm fund` for details

upload [12] mqtt.admin /opt/iobroker/node_modules/iobroker.mqtt/admin/i18n/de/translations.json i18n/de/translations.json application/json

upload [11] mqtt.admin /opt/iobroker/node_modules/iobroker.mqtt/admin/i18n/en/translations.json i18n/en/translations.json application/json

upload [10] mqtt.admin /opt/iobroker/node_modules/iobroker.mqtt/admin/i18n/es/translations.json i18n/es/translations.json application/json

upload [9] mqtt.admin /opt/iobroker/node_modules/iobroker.mqtt/admin/i18n/fr/translations.json i18n/fr/translations.json application/json

upload [8] mqtt.admin /opt/iobroker/node_modules/iobroker.mqtt/admin/i18n/it/translations.json i18n/it/translations.json application/json

upload [7] mqtt.admin /opt/iobroker/node_modules/iobroker.mqtt/admin/i18n/nl/translations.json i18n/nl/translations.json application/json

upload [6] mqtt.admin /opt/iobroker/node_modules/iobroker.mqtt/admin/i18n/pl/translations.json i18n/pl/translations.json application/json

upload [5] mqtt.admin /opt/iobroker/node_modules/iobroker.mqtt/admin/i18n/pt/translations.json i18n/pt/translations.json application/json

upload [4] mqtt.admin /opt/iobroker/node_modules/iobroker.mqtt/admin/i18n/ru/translations.json i18n/ru/translations.json application/json

upload [3] mqtt.admin /opt/iobroker/node_modules/iobroker.mqtt/admin/i18n/zh-cn/translations.json i18n/zh-cn/translations.json application/json

upload [2] mqtt.admin /opt/iobroker/node_modules/iobroker.mqtt/admin/index_m.html index_m.html text/html

upload [1] mqtt.admin /opt/iobroker/node_modules/iobroker.mqtt/admin/jsonConfig.json jsonConfig.json application/json

upload [0] mqtt.admin /opt/iobroker/node_modules/iobroker.mqtt/admin/mqtt.png mqtt.png image/png

Update "system.adapter.mqtt.1"

Update "system.adapter.mqtt.2"

Process exited with code 0`

After that I had to update my admin, because of the following errors:

`host.MWHome
2022-05-17 15:12:29.794	error	startInstance system.adapter.mqtt.2 Adapter dependency not fulfilled on any host: required adapter "admin" has wrong version. Installed "5.3.8", required ">=5.4.3"!
host.MWHome
2022-05-17 15:12:29.715	error	startInstance system.adapter.mqtt.1 Adapter dependency not fulfilled on any host: required adapter "admin" has wrong version. Installed "5.3.8", required ">=5.4.3"!`

After upgrade my mqtt .1 instance started properly - as it only refers to mqtt scope. 

![image](https://user-images.githubusercontent.com/58858526/168828202-f7fd624e-2f3e-413e-8763-bc57af76e615.png)

The mqtt.2 - instance however stopped with errors, even if the mask seems that the existing parameters were taken over.

![image](https://user-images.githubusercontent.com/58858526/168827796-6acfdc34-2c0e-467e-b41e-63f34aa358c5.png)

I had it running after saving the adapter configuration. Then after I set the adapter back to info level - and got again errors and the adapter did no longer start.

[LOG - File.zip](https://github.com/ioBroker/ioBroker.mqtt/files/8708967/LOG.-.File.zip)

So at the end it is not fixed!!

Here the current status:

`<html>
<body>


2022-05-17 16:13:59.155 - info: host.MWHome Restart adapter system.adapter.mqtt.2 because enabled
--
2022-05-17 16:14:29.280 - info: host.MWHome instance system.adapter.mqtt.2 started with pid 19110
2022-05-17 16:14:32.167 - info: mqtt.2 (19110) starting. Version 4.0.2 (non-npm: ioBroker/ioBroker.mqtt) in /opt/iobroker/node_modules/iobroker.mqtt, node: v14.19.2, js-controller: 4.0.23
2022-05-17 16:14:32.635 - info: mqtt.2 (19110) Try to connect to mqtt://localhost:1883 with clientId=mqttClientIobrokerPublishOnlyand credentials mwmqtt4iob:*******************
2022-05-17 16:14:32.750 - info: mqtt.2 (19110) Connected to localhost
2022-05-17 16:14:32.753 - info: mqtt.2 (19110) Subscribe on "iobroker/#"
2022-05-17 16:14:32.792 - info: mqtt.2 (19110) send2Server mqtt.2.info.connection[iobroker/info/connection]
2022-05-17 16:14:33.212 - error: mqtt.2 (19110) uncaught exception: Cannot read property 'common' of null
2022-05-17 16:14:33.212 - error: mqtt.2 (19110) TypeError: Cannot read property 'common' of null
at publishMessage (/opt/iobroker/node_modules/iobroker.mqtt/lib/client.js:109:43)
at send2Server (/opt/iobroker/node_modules/iobroker.mqtt/lib/client.js:87:9)
at MQTTClient.onStateChange (/opt/iobroker/node_modules/iobroker.mqtt/lib/client.js:33:41)
at Adapter. (/opt/iobroker/node_modules/iobroker.mqtt/main.js:76:34)
at Adapter.emit (events.js:400:28)
at Adapter.emit (domain.js:475:12)
at Immediate. (/opt/iobroker/node_modules/@iobroker/js-controller-adapter/src/lib/adapter/adapter.js:5912:53)
at processImmediate (internal/timers.js:464:21)
2022-05-17 16:14:33.213 - error: mqtt.2 (19110) Cannot read property 'common' of null
2022-05-17 16:14:33.237 - error: mqtt.2 (19110) uncaughtException: TypeError: Cannot read property 'common' of null
2022-05-17 16:14:33.253 - info: mqtt.2 (19110) Disconnected from localhost: undefined
2022-05-17 16:14:33.745 - info: mqtt.2 (19110) terminating
2022-05-17 16:14:33.747 - warn: mqtt.2 (19110) Terminated (UNCAUGHT_EXCEPTION): Without reason
2022-05-17 16:14:34.400 - error: host.MWHome Caught by controller[0]: TypeError: Cannot read property 'common' of null
2022-05-17 16:14:34.401 - error: host.MWHome Caught by controller[0]: at publishMessage (/opt/iobroker/node_modules/iobroker.mqtt/lib/client.js:109:43)
2022-05-17 16:14:34.401 - error: host.MWHome Caught by controller[0]: at send2Server (/opt/iobroker/node_modules/iobroker.mqtt/lib/client.js:87:9)
2022-05-17 16:14:34.402 - error: host.MWHome Caught by controller[0]: at MQTTClient.onStateChange (/opt/iobroker/node_modules/iobroker.mqtt/lib/client.js:33:41)
2022-05-17 16:14:34.402 - error: host.MWHome Caught by controller[0]: at Adapter. (/opt/iobroker/node_modules/iobroker.mqtt/main.js:76:34)
2022-05-17 16:14:34.402 - error: host.MWHome Caught by controller[0]: at Adapter.emit (events.js:400:28)
2022-05-17 16:14:34.402 - error: host.MWHome Caught by controller[0]: at Adapter.emit (domain.js:475:12)
2022-05-17 16:14:34.403 - error: host.MWHome Caught by controller[0]: at Immediate. (/opt/iobroker/node_modules/@iobroker/js-controller-adapter/src/lib/adapter/adapter.js:5912:53)
2022-05-17 16:14:34.403 - error: host.MWHome Caught by controller[0]: at processImmediate (internal/timers.js:464:21)
2022-05-17 16:14:34.403 - error: host.MWHome instance system.adapter.mqtt.2 terminated with code 6 (UNCAUGHT_EXCEPTION)
2022-05-17 16:14:34.403 - info: host.MWHome Restart adapter system.adapter.mqtt.2 because enabled
2022-05-17 16:14:44.792 - info: host.MWHome "system.adapter.mqtt.2" disabled


</body>
</html>`

**Comment by GermanBluefox** [comment]
Please Try again with 4.0.3

**Comment by mickym2** [comment]
I reopen this - as I am not sure if there is something wrong or if now an endless loop or something is active. Since the adapter update with subscription of tr-064 data - the tr-064 or the FB crashes. I switched to debug and will see - if I can detect something. However it is noticeable that this crashes occur since the update - and I had no problems before. So I will watch and update this if I will detect something which is not normal.
