### ISSUE TITLE
MQTT: Does not start up

### ISSUE THREAD

**Issue by fah** [ioBroker/ioBroker.mqtt#296]
**Describe the bug**  
MQTT does not start after beta update

**To Reproduce**  
I made an iob update 4.0.21->4.0.23

**Expected behavior**  
All three lamps of mqtt green

**Screenshots & Logfiles**  

![grafik](https://user-images.githubusercontent.com/322496/169665700-48553253-905b-43c6-a3f7-982e9a610427.png)

pi@rp41:~ $ tail -50 /opt/iobroker/log/iobroker.current.log 
```log
2022-05-21 20:12:39.787  - info: host.rp41 "system.adapter.mqtt.0" enabled
2022-05-21 20:12:40.166  - info: host.rp41 instance system.adapter.mqtt.0 started with pid 28902
2022-05-21 20:12:41.398  - error: host.rp41 Caught by controller[0]: internal/modules/cjs/loader.js:818
2022-05-21 20:12:41.398  - error: host.rp41 Caught by controller[0]:   throw err;
2022-05-21 20:12:41.398  - error: host.rp41 Caught by controller[0]:   ^
2022-05-21 20:12:41.398  - error: host.rp41 Caught by controller[0]: Error: Cannot find module 'semver'
2022-05-21 20:12:41.399  - error: host.rp41 Caught by controller[0]: Require stack:
2022-05-21 20:12:41.400  - error: host.rp41 Caught by controller[0]: - /opt/iobroker/node_modules/iobroker.mqtt/main.js
2022-05-21 20:12:41.400  - error: host.rp41 Caught by controller[0]:     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:815:15)
2022-05-21 20:12:41.400  - error: host.rp41 Caught by controller[0]:     at Function.Module._load (internal/modules/cjs/loader.js:667:27)
2022-05-21 20:12:41.400  - error: host.rp41 Caught by controller[0]:     at Module.require (internal/modules/cjs/loader.js:887:19)
2022-05-21 20:12:41.400  - error: host.rp41 Caught by controller[0]:     at require (internal/modules/cjs/helpers.js:74:18)
2022-05-21 20:12:41.401  - error: host.rp41 Caught by controller[0]:     at Object.<anonymous> (/opt/iobroker/node_modules/iobroker.mqtt/main.js:13:16)
2022-05-21 20:12:41.401  - error: host.rp41 Caught by controller[0]:     at Module._compile (internal/modules/cjs/loader.js:999:30)
2022-05-21 20:12:41.401  - error: host.rp41 Caught by controller[0]:     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
2022-05-21 20:12:41.401  - error: host.rp41 Caught by controller[0]:     at Module.load (internal/modules/cjs/loader.js:863:32)
2022-05-21 20:12:41.402  - error: host.rp41 Caught by controller[0]:     at Function.Module._load (internal/modules/cjs/loader.js:708:14)
2022-05-21 20:12:41.402  - error: host.rp41 Caught by controller[0]:     at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:60:12) {
2022-05-21 20:12:41.402  - error: host.rp41 Caught by controller[0]:   code: 'MODULE_NOT_FOUND',
2022-05-21 20:12:41.402  - error: host.rp41 Caught by controller[0]:   requireStack: [ '/opt/iobroker/node_modules/iobroker.mqtt/main.js' ]
2022-05-21 20:12:41.402  - error: host.rp41 Caught by controller[0]: }
2022-05-21 20:12:41.403  - error: host.rp41 instance system.adapter.mqtt.0 terminated with code 1 (JS_CONTROLLER_STOPPED)
```

**Versions:**  
Full update date: 21.05.22 20:12
mqtt 4.0.3
iobroker -v 4.0.23
node -v v12.22.12
NPM: 6.14.16
"npm ls" is attached [npm-ls.txt](https://github.com/ioBroker/ioBroker.mqtt/files/8748171/npm-ls.txt)

**Comment by fah** [comment]
```sh
/opt/iobroker/node_modules/mqtt $ npm install --production
```
did not help.
