### ISSUE TITLE
v. 2.0.4 uncaught exception: Cannot read property 'topic' of undefined

### ISSUE THREAD

**Issue by instalator** [ioBroker/ioBroker.mqtt#38]
```
2019-01-09 11:20:03.928  - [31merror[39m: mqtt.0 uncaught exception: Cannot read property 'topic' of undefined
2019-01-09 11:20:03.952  - [31merror[39m: mqtt.0 TypeError: Cannot read property 'topic' of undefined
    at receivedTopic (C:\ioBroker\node_modules\iobroker.mqtt\lib\server.js:406:31)
    at Connection.client.on.packet (C:\ioBroker\node_modules\iobroker.mqtt\lib\server.js:820:21)
    at emitOne (events.js:96:13)
    at Connection.emit (events.js:188:7)
    at Connection.emitPacket (C:\ioBroker\node_modules\iobroker.mqtt\node_modules\mqtt-connection\connection.js:10:8)
    at emitOne (events.js:96:13)
    at Connection.emit (events.js:188:7)
    at addChunk (C:\ioBroker\node_modules\iobroker.mqtt\node_modules\readable-stream\lib\_stream_readable.js:291:12)
    at readableAddChunk (C:\ioBroker\node_modules\iobroker.mqtt\node_modules\readable-stream\lib\_stream_readable.js:278:11)
    at Connection.Duplexify._forward (C:\ioBroker\node_modules\iobroker.mqtt\node_modules\duplexify\index.js:170:26)
    at DestroyableTransform.onreadable (C:\ioBroker\node_modules\iobroker.mqtt\node_modules\duplexify\index.js:134:10)
2019-01-09 11:20:04.495  - [32minfo[39m: mqtt.0 terminating
2019-01-09 11:20:05.384  - [31merror[39m: Caught by controller[0]: TypeError: Cannot read property 'topic' of undefined
2019-01-09 11:20:05.393  - [31merror[39m: Caught by controller[0]:     at receivedTopic (C:\ioBroker\node_modules\iobroker.mqtt\lib\server.js:406:31)
2019-01-09 11:20:05.394  - [31merror[39m: Caught by controller[0]:     at Connection.client.on.packet (C:\ioBroker\node_modules\iobroker.mqtt\lib\server.js:820:21)
2019-01-09 11:20:05.394  - [31merror[39m: Caught by controller[0]:     at emitOne (events.js:96:13)
2019-01-09 11:20:05.395  - [31merror[39m: Caught by controller[0]:     at Connection.emit (events.js:188:7)
2019-01-09 11:20:05.395  - [31merror[39m: Caught by controller[0]:     at Connection.emitPacket (C:\ioBroker\node_modules\iobroker.mqtt\node_modules\mqtt-connection\connection.js:10:8)
2019-01-09 11:20:05.396  - [31merror[39m: Caught by controller[0]:     at emitOne (events.js:96:13)
2019-01-09 11:20:05.396  - [31merror[39m: Caught by controller[0]:     at Connection.emit (events.js:188:7)
2019-01-09 11:20:05.397  - [31merror[39m: Caught by controller[0]:     at addChunk (C:\ioBroker\node_modules\iobroker.mqtt\node_modules\readable-stream\lib\_stream_readable.js:291:12)
2019-01-09 11:20:05.398  - [31merror[39m: Caught by controller[0]:     at readableAddChunk (C:\ioBroker\node_modules\iobroker.mqtt\node_modules\readable-stream\lib\_stream_readable.js:278:11)
2019-01-09 11:20:05.398  - [31merror[39m: Caught by controller[0]:     at Connection.Duplexify._forward (C:\ioBroker\node_modules\iobroker.mqtt\node_modules\duplexify\index.js:170:26)
2019-01-09 11:20:05.399  - [31merror[39m: Caught by controller[0]:     at DestroyableTransform.onreadable (C:\ioBroker\node_modules\iobroker.mqtt\node_modules\duplexify\index.js:134:10)
2019-01-09 11:20:05.399  - [31merror[39m: Caught by controller[1]: 2019-01-09 11:20:03.949  -  mqtt.0 uncaught exception: Cannot read property 'topic' of undefined

2019-01-09 11:20:05.400  - [31merror[39m: Caught by controller[2]: 2019-01-09 11:20:03.953  -  mqtt.0 TypeError: Cannot read property 'topic' of undefined
2019-01-09 11:20:05.401  - [31merror[39m: Caught by controller[2]:     at receivedTopic (C:\ioBroker\node_modules\iobroker.mqtt\lib\server.js:406:31)
2019-01-09 11:20:05.401  - [31merror[39m: Caught by controller[2]:     at Connection.client.on.packet (C:\ioBroker\node_modules\iobroker.mqtt\lib\server.js:820:21)
2019-01-09 11:20:05.402  - [31merror[39m: Caught by controller[2]:     at emitOne (events.js:96:13)
2019-01-09 11:20:05.402  - [31merror[39m: Caught by controller[2]:     at Connection.emit (events.js:188:7)
2019-01-09 11:20:05.403  - [31merror[39m: Caught by controller[2]:     at Connection.emitPacket (C:\ioBroker\node_modules\iobroker.mqtt\node_modules\mqtt-connection\connection.js:10:8)
2019-01-09 11:20:05.403  - [31merror[39m: Caught by controller[2]:     at emitOne (events.js:96:13)
2019-01-09 11:20:05.404  - [31merror[39m: Caught by controller[2]:     at Connection.emit (events.js:188:7)
2019-01-09 11:20:05.404  - [31merror[39m: Caught by controller[2]:     at addChunk (C:\ioBroker\node_modules\iobroker.mqtt\node_modules\readable-stream\lib\_stream_readable.js:291:12)
2019-01-09 11:20:05.405  - [31merror[39m: Caught by controller[2]:     at readableAddChunk (C:\ioBroker\node_modules\iobroker.mqtt\node_modules\readable-stream\lib\_stream_readable.js:278:11)
2019-01-09 11:20:05.405  - [31merror[39m: Caught by controller[2]:     at Connection.Duplexify._forward (C:\ioBroker\node_modules\iobroker.mqtt\node_modules\duplexify\index.js:170:26)
2019-01-09 11:20:05.406  - [31merror[39m: Caught by controller[2]:     at DestroyableTransform.onreadable (C:\ioBroker\node_modules\iobroker.mqtt\node_modules\duplexify\index.js:134:10)

2019-01-09 11:20:05.407  - [31merror[39m: host.SERVER instance system.adapter.mqtt.0 terminated with code 0 (OK)
2019-01-09 11:20:05.407  - [32minfo[39m: host.SERVER Restart adapter system.adapter.mqtt.0 because enabled
```

**Comment by instalator** [comment]
Apparently the client is not working steadily because of the power supply, but I would like to exclude driver drops due to such errors.

![image](https://user-images.githubusercontent.com/11523624/50903266-e47ed500-144f-11e9-9fc5-76ba5ec65318.png)

**Comment by Waly-de** [comment]
The same problem with me.

`
2019-04-02 20:57:13.209 - error: mqtt.0 uncaught exception: Cannot read property 'topic' of undefined
--
2019-04-02 20:57:13.211 - error: mqtt.0 TypeError: Cannot read property 'topic' of undefined
at receivedTopic (/opt/iobroker/node_modules/iobroker.mqtt/lib/server.js:406:32)
at Connection.client.on.packet (/opt/iobroker/node_modules/iobroker.mqtt/lib/server.js:820:21)
at emitOne (events.js:116:13)
at Connection.emit (events.js:211:7)
at Connection.emitPacket (/opt/iobroker/node_modules/mqtt-connection/connection.js:10:8)
at emitOne (events.js:116:13)
at Connection.emit (events.js:211:7)
at addChunk (/opt/iobroker/node_modules/duplexify/node_modules/readable-stream/lib/_stream_readable.js:291:12)
at readableAddChunk (/opt/iobroker/node_modules/duplexify/node_modules/readable-stream/lib/_stream_readable.js:278:11)
at Connection.Readable.push (/opt/iobroker/node_modules/duplexify/node_modules/readable-stream/lib/_stream_readable.js:245:10)
2019-04-02 20:57:13.721 - info: mqtt.0 terminating
2019-04-02 20:57:13.819 - error: Caught by controller[0]: TypeError: Cannot read property 'topic' of undefined
2019-04-02 20:57:13.820 - error: Caught by controller[0]: at receivedTopic (/opt/iobroker/node_modules/iobroker.mqtt/lib/server.js:406:32)
2019-04-02 20:57:13.821 - error: Caught by controller[0]: at Connection.client.on.packet (/opt/iobroker/node_modules/iobroker.mqtt/lib/server.js:820:21)
2019-04-02 20:57:13.821 - error: Caught by controller[0]: at emitOne (events.js:116:13)
2019-04-02 20:57:13.821 - error: Caught by controller[0]: at Connection.emit (events.js:211:7)
2019-04-02 20:57:13.821 - error: Caught by controller[0]: at Connection.emitPacket (/opt/iobroker/node_modules/mqtt-connection/connection.js:10:8)
2019-04-02 20:57:13.822 - error: Caught by controller[0]: at emitOne (events.js:116:13)
2019-04-02 20:57:13.822 - error: Caught by controller[0]: at Connection.emit (events.js:211:7)
2019-04-02 20:57:13.822 - error: Caught by controller[0]: at addChunk (/opt/iobroker/node_modules/duplexify/node_modules/readable-stream/lib/_stream_readable.js:291:12)
2019-04-02 20:57:13.822 - error: Caught by controller[0]: at readableAddChunk (/opt/iobroker/node_modules/duplexify/node_modules/readable-stream/lib/_stream_readable.js:278:11)
2019-04-02 20:57:13.823 - error: Caught by controller[0]: at Connection.Readable.push (/opt/iobroker/node_modules/duplexify/node_modules/readable-stream/lib/_stream_readable.js:245:10)
2019-04-02 20:57:13.823 - error: host.rock64 instance system.adapter.mqtt.0 terminated with code 0 (OK)
`

I took a look into the line:
/opt/iobroker/node_modules/iobroker.mqtt/lib/server.js:820:21 

in line 816 i found :   `if (pos !== -1) { `
i don't really understand what is happening there but i replaced it with:
 `if (pos !== null && pos !== -1) { `
because of the 
`let pos = null;`
in line 808

and hope that fixed the problem for me and helps you to really fix the bug ;-)
