### ISSUE TITLE
MQTT Topics ignorieren funktioniert nicht

### ISSUE THREAD

**Issue by Rushmed** [ioBroker/ioBroker.mqtt#429]
Hallo,

ich habe hier drei MQTT Clients die extrem viele Topics senden.
Davon würde ich gerne welche über diese Funktion abbestellen:

Ich hoffe das ist so gedacht!?
Die MQTT Instanz ist der Server.
![image](https://github.com/ioBroker/ioBroker.mqtt/assets/59259796/2fbe5596-065a-410f-a4c9-7da9a08471a5)
Ignorieren möchte ich alles unter:
mqtt.0.instar.all.alarm.*
mqtt.0.instar.cam_10.alarm.*
und
mqtt.0.instar.cam_11.alarm.*

Lösche ich nun alle Objekte und gebe ich im Feld ".alarm.*" ein werden diese trotzdem wieder erstellt.

Was mache ich falsch?

Adapter 5.2
![image](https://github.com/ioBroker/ioBroker.mqtt/assets/59259796/3d2929f4-8d85-42b1-97ca-e2fabe13dd01)

Es gibt schon ein Forumsbeitrag dazu.

**Comment by hschwane** [comment]
Have the same problem. Even without using wildcards nothing is actually ignored.

**Comment by j64bit** [comment]
I have the same problem. When to-be-rejected message is received, then the apdapter crashes with these error messages:

```
2025-12-13 16:03:20.107  - error:  mqtt.0 (182978) Unhandled promise rejection. This error originated  either by throwing inside of an async function without a catch block, or  by rejecting a promise which was not handled with .catch().
2025-12-13 16:03:20.110  - error: mqtt.0 (182978) unhandled promise rejection: Cannot read properties of undefined (reading 'id')
2025-12-13 16:03:20.110  - error: mqtt.0 (182978) TypeError: Cannot read properties of undefined (reading 'id')
at Connection. (/opt/iobroker/node_modules/iobroker.mqtt/lib/server.js:1213:56)
at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
2025-12-13 16:03:20.111  - error: mqtt.0 (182978) Cannot read properties of undefined (reading 'id')
2025-12-13 16:03:20.117  - warn: mqtt.0 (182978) Terminated (UNCAUGHT_EXCEPTION): Without reason
2025-12-13 16:03:20.622  - warn: mqtt.0 (182978) Cannot get view: Connection is closed.
2025-12-13 16:03:20.746  - error: host.iobroker instance system.adapter.mqtt.0 terminated with code 6 (UNCAUGHT_EXCEPTION)
2025-12-13 16:03:55.655  - error:  mqtt.0 (183004) Unhandled promise rejection. This error originated  either by throwing inside of an async function without a catch block, or  by rejecting a promise which was not handled with .catch().
2025-12-13 16:03:55.657  - error: mqtt.0 (183004) unhandled promise rejection: Cannot read properties of undefined (reading 'id')
2025-12-13 16:03:55.658  - error: mqtt.0 (183004) TypeError: Cannot read properties of undefined (reading 'id')
at Connection. (/opt/iobroker/node_modules/iobroker.mqtt/lib/server.js:1213:56)
at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
2025-12-13 16:03:55.658  - error: mqtt.0 (183004) Cannot read properties of undefined (reading 'id')
2025-12-13 16:03:55.662  - warn: mqtt.0 (183004) Terminated (UNCAUGHT_EXCEPTION): Without reason
2025-12-13 16:03:56.168  - warn: mqtt.0 (183004) Cannot get view: Connection is closed.
2025-12-13 16:03:56.277  - error: host.iobroker instance system.adapter.mqtt.0 terminated with code 6 (UNCAUGHT_EXCEPTION)
2025-12-13 16:04:31.209  - error:  mqtt.0 (183096) Unhandled promise rejection. This error originated  either by throwing inside of an async function without a catch block, or  by rejecting a promise which was not handled with .catch().
2025-12-13 16:04:31.212  - error: mqtt.0 (183096) unhandled promise rejection: Cannot read properties of undefined (reading 'id')
2025-12-13 16:04:31.212  - error: mqtt.0 (183096) TypeError: Cannot read properties of undefined (reading 'id')
at Connection. (/opt/iobroker/node_modules/iobroker.mqtt/lib/server.js:1213:56)
at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
2025-12-13 16:04:31.212  - error: mqtt.0 (183096) Cannot read properties of undefined (reading 'id')
2025-12-13 16:04:31.216  - warn: mqtt.0 (183096) Terminated (UNCAUGHT_EXCEPTION): Without reason
2025-12-13 16:04:31.722  - warn: mqtt.0 (183096) Cannot get view: Connection is closed.
2025-12-13 16:04:31.842  - error: host.iobroker instance system.adapter.mqtt.0 terminated with code 6 (UNCAUGHT_EXCEPTION)
2025-12-13 16:04:31.843  - warn: host.iobroker Do not restart adapter system.adapter.mqtt.0 because restart loop detected
```

I would like to block all "homeassistant.*"  messages :-)

**Comment by TobiasSt78** [comment]
I can confirm this on a current version, in **server (broker) mode** — with some numbers,
in case they help narrowing it down.

## Setup

- mqtt adapter version: v8.0.1
- js-controller: 7.2.2
- Mode: server (broker), evcc and a number of ESP devices publishing to it
- ~1,550 objects below `mqtt.0`, of which ~1,100 came from a single chatty client (evcc)

## What happens

`ignoredTopics` has no effect at all here. My list contains 93 patterns written exactly
as the field's own help text suggests (`These topics will be ignored on receiving
(Divided by comma, e.g. 'mqtt.0.*,javascript.*')`), for example:

`mqtt.0.evcc.site.ext*., mqtt.0.evcc.loadpoints..plan*, mqtt.0.warmepumpe.*`

I deleted 1,233 matching objects. After restarting the instance, **450 of the 773 objects
that were present again matched an entry in `ignoredTopics`** — they had been recreated
despite the filter.

Notably, some of those patterns had been in my configuration for a long time. That
explains why objects I believed to be filtered had been sitting in the object tree all
along: the setting has apparently never had any effect in my installation.

## Workaround, and its side effects

The only thing that reliably stops the recreation is the checkbox **"Do not create new
states"** (`ignoreNewObjects`). With it enabled the object count stays stable at 316.

Two drawbacks, though:

1. The adapter now logs one **warning per ignored topic**:
   `Object mqtt.0.evcc.loadpoints.2.effectivePlanSoc ignored and not created`
   With a client like evcc that republishes its full state on reconnect, that is several
   hundred warnings per restart.
2. It is all-or-nothing — a genuinely new device is not created either, so the checkbox
   has to be toggled off and on whenever something new is added.

Both would be non-issues if `ignoredTopics` worked, since the point of the setting is
exactly this selective filtering.

## Suggestions

- Apply `ignoredTopics` in server mode as well (I cannot say whether client mode is
  affected — I only run server mode).
- Log the "ignored and not created" message at `debug` level, or suppress it for topics
  that match `ignoredTopics`, so the intended behaviour does not flood the log.

Happy to test a fix or provide the full object export / configuration if that helps.
