### ISSUE TITLE
Issue with js-controller 2.0

### ISSUE THREAD

**Issue by cburghardt** [ioBroker/ioBroker.mqtt#69]
Since upgrading to js-controller 2.0.35 I get the following warnings from MQTT:

```
2019-10-24 13:06:48.333  - warn: mqtt.0 (498) States pmessage io.messagebox.system.adapter.mqtt.0 [object Object] "string" must be a string, Buffer, or ArrayBuffer
2019-10-24 13:06:48.335  - warn: mqtt.0 (498) TypeError: "string" must be a string, Buffer, or ArrayBuffer
    at Function.byteLength (buffer.js:481:11)
    at publish (/opt/iobroker/node_modules/iobroker.mqtt/node_modules/mqtt-packet/writeToStream.js:275:51)
    at Object.generate [as writeToStream] (/opt/iobroker/node_modules/iobroker.mqtt/node_modules/mqtt-packet/writeToStream.js:33:14)
    at sendPacket (/opt/iobroker/node_modules/iobroker.mqtt/node_modules/mqtt/lib/client.js:37:27)
    at storedPacket (/opt/iobroker/node_modules/iobroker.mqtt/node_modules/mqtt/lib/client.js:62:5)
    at Store.put (/opt/iobroker/node_modules/iobroker.mqtt/node_modules/mqtt/lib/store.js:54:5)
    at storeAndSend (/opt/iobroker/node_modules/iobroker.mqtt/node_modules/mqtt/lib/client.js:58:24)
    at MqttClient._sendPacket (/opt/iobroker/node_modules/iobroker.mqtt/node_modules/mqtt/lib/client.js:831:7)
    at MqttClient.publish (/opt/iobroker/node_modules/iobroker.mqtt/node_modules/mqtt/lib/client.js:428:12)
    at publishMessage (/opt/iobroker/node_modules/iobroker.mqtt/lib/client.js:74:10)
```

**Comment by cburghardt** [comment]
More information: the source is a call which contains a buffer:

```
        var fs = require('fs');
        fs.readFile('/opt/iobroker/cache/alarm.wav', function (err, data) {
            if (err) log(err, "warn");
            else {
                sendTo('mqtt.0', 'sendMessage2Client', {topic: 'hermes/audioServer/living-room/playBytes/'+Math.random().toString(36).slice(-5), message: data});
            }
        });
```
This worked with js-controller 1.5.
@GermanBluefox is that a regression?

**Comment by Apollon77** [comment]
fixed by js.-controller 2.0.36 (currently GitHub)
