### ISSUE TITLE
Error if persistent mode is used

### ISSUE THREAD

**Issue by Boldie** [ioBroker/ioBroker.mqtt#76]
Hi,

I used the mqtt adapter and if I enable persistent mode, the adapter crashes.

host.iobroker | 2020-02-16 21:46:08.153 | info | Restart adapter system.adapter.mqtt.0 because enabled
-- | -- | -- | --
host.iobroker | 2020-02-16 21:46:08.153 | info | instance system.adapter.mqtt.0 terminated with code 0 (NO_ERROR)
host.iobroker | 2020-02-16 21:46:08.153 | error | Caught by controller[0]:     at process._tickCallback (internal/process/next_tick.js:68:7)
host.iobroker | 2020-02-16 21:46:08.153 | error | Caught by controller[0]:     at promise.then (/opt/iobroker/node_modules/standard-as-callback/built/index.js:19:49)
host.iobroker | 2020-02-16 21:46:08.153 | error | Caught by controller[0]:     at tryCatcher (/opt/iobroker/node_modules/standard-as-callback/built/utils.js:11:23)
host.iobroker | 2020-02-16 21:46:08.153 | error | Caught by controller[0]:     at client.get  (/opt/iobroker/node_modules/iobroker.js-controller/lib/states/statesInRedis.js:580:17)
host.iobroker | 2020-02-16 21:46:08.152 | error | Caught by controller[0]:     at adapter.getState (/opt/iobroker/node_modules/iobroker.mqtt/lib/client.js:371:49)
host.iobroker | 2020-02-16 21:46:08.152 | error | Caught by controller[0]:     at JSON.parse (<anonymous>)
host.iobroker | 2020-02-16 21:46:08.152 | error | Caught by controller[0]: SyntaxError: Unexpected end of JSON input
mqtt.0 | 2020-02-16 21:46:07.641 | info | (1378) Terminated (NO_ERROR): Without reason
mqtt.0 | 2020-02-16 21:46:07.640 | info | (1378) terminating
mqtt.0 | 2020-02-16 21:46:07.146 | info | (1378) Disconnected from mosquitto: undefined
mqtt.0 | 2020-02-16 21:46:07.135 | error | (1378) uncaughtException: SyntaxError: Unexpected end of JSON input
mqtt.0 | 2020-02-16 21:46:07.134 | error | at process._tickCallback (internal/process/next_tick.js:68:7)
mqtt.0 | 2020-02-16 21:46:07.134 | error | at promise.then (/opt/iobroker/node_modules/standard-as-callback/built/index.js:19:49)
mqtt.0 | 2020-02-16 21:46:07.134 | error | at tryCatcher (/opt/iobroker/node_modules/standard-as-callback/built/utils.js:11:23)
mqtt.0 | 2020-02-16 21:46:07.134 | error | at client.get (/opt/iobroker/node_modules/iobroker.js-controller/lib/states/statesInRedis.js:580:17)
mqtt.0 | 2020-02-16 21:46:07.134 | error | at adapter.getState (/opt/iobroker/node_modules/iobroker.mqtt/lib/client.js:371:49)
mqtt.0 | 2020-02-16 21:46:07.134 | error | at JSON.parse (<anonymous>)
mqtt.0 | 2020-02-16 21:46:07.134 | error | (1378) SyntaxError: Unexpected end of JSON input
mqtt.0 | 2020-02-16 21:46:07.134 | error | (1378) uncaught exception: Unexpected end of JSON input

**Comment by Boldie** [comment]
The problem seems to be the info.lastSession is not initialized after installation and thus this stuff in node_modules/iobroker.mqtt/lib/client.js:370 fails. How to initialize this lastSession thing?

Writing [] to this node will fix this problem.
